version: '3.9'

services: 
  mysql:
    container_name: ${MYSQL_NAME}
    image: mysql
    restart: unless-stopped
    ports: 
      - '${MYSQL_NAME}:3606'

  backend:
    container_name: '${API_NAME}'
    build: ./
    ports:
      - '3333:3333'
    command: yarn dev:server
    depends_on: 
      - mysql